# Generated by Django 4.2.7 on 2023-11-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
