# Generated by Django 4.2.1 on 2023-06-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('comments', models.CharField(max_length=32)),
                ('date', models.IntegerField(max_length=16)),
                ('ratings', models.IntegerField(max_length=5)),
            ],
        ),
    ]
