# Generated by Django 4.2.1 on 2023-06-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_details', models.CharField(max_length=32)),
                ('order_status', models.CharField(max_length=32)),
                ('items', models.CharField(max_length=32)),
                ('customer_information', models.CharField(max_length=32)),
            ],
        ),
    ]
