# Generated by Django 4.2.7 on 2023-11-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventory_product'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
